### ISSUE TITLE
优化建议：优化从环境变量中读取KEY时的ZhipuAI初始化调用

### ISSUE THREAD

**Issue by stargatejy** [MetaGLM/zhipuai-sdk-nodejs-v4#3]
目前如果在环境变量中设置了API Key，ZhipuAI初始化仍然需要带apiKey的参数，如果不带则报错，如下：
const zhipuai = new ZhipuAI({apiKey: ''});

建议修改为与OpenAI的调用一致，如果在环境变量中设置了API Key，初始化时不加参数，如：
const zhipuai = new ZhipuAI();

**Comment by winily** [comment]
现在是必须传入一个 options 对象，可以是个空对象，不过你这个建议会接纳
